const CoursesData = [
    {
        'id':1,
    'Title':'Questions',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'id':2,
    'Title':'Algorithms',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'id':3,
    'Title':'Scripts',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'id':4,
    'Title':'Games',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'id':5,
    'Title':'File Handling',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'id':6,
    'Title':'Videos',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'id':7,
    'Title':'Quizes',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'id':8,
    'Title':'Documentation',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},

{
    'id':9,
    'Title':'Popular Repos',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'id':10,
    'Title':'Interview Questions',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},

{
    'id':11,
    'Title':'Resumes',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'id':12,
    'Title':'Projects',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},

]


export default CoursesData;