const CoursesData = [
    {
    'Title':'Questions',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'Title':'Algorithms',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'Title':'Scripts',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'Title':'Games',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'Title':'File Handling',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'Title':'Videos',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'Title':'Quizes',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'Title':'Documentation',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},

{
    'Title':'Popular Repos',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'Title':'Interview Questions',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},

{
    'Title':'Resumes',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},
{
    'Title':'Projects',
    'Description':'CODE COINS CAN BE USED IN MULTIPLE PLACES THROUGH OUT THE APP,LIKE FOR BUYING COURSES,CHALLENGES,QUESTIONS.'
},

]


export default CoursesData;